// Suggested tags for contacts, especially colaboradores
export const SUGGESTED_CONTACT_TAGS = [
  'Circulo',
  'Zona',
  'Prescriptor',
  'Recomendador',
  'Oro',
  'Plata',
  'Bronce',
  'Cliente cerrado',
  'Influenciador local',
  'Notaría',
  'Gestoría',
  'Admin. fincas',
  'Banco',
  'Tasador',
  'Arquitecto',
  'Abogado',
  'Reformista',
  'Decorador',
  'Fotógrafo',
  'Home staging',
  'Hipotecas',
  'Seguros',
  'Mudanzas',
  'Cerrajero',
  'Electricista',
  'Fontanero',
  'Inversor',
  'Promotor',
  'API externo',
];
